const ArticleTag = Object.freeze({
  TRAINING: "TRAINING",
  NUTRITION: "NUTRITION",
  RECOVERY: "RECOVERY",
  PHYSIOLOGY: "PHYSIOLOGY",
  PSYCHOLOGY: "PSYCHOLOGY",
  BIOMECHANICS: "BIOMECHANICS",
  PERIODIZATION: "PERIODIZATION",
});

module.exports = ArticleTag;
